data "aws_region" "current" { }
locals {
    region = data.aws_region.current.name
}
resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = "EC2-API-Dashboard"

  dashboard_body = jsonencode({
    "widgets":[
       {
          "type":"metric",
          "x":0,
          "y":4,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   {
                      "id":"m1"
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"All EC2 API Actions RequestLimitExceeded",
             "yAxis":{
                "left":{
                   "label":"API Calls",
                   "showUnits":false,
                   "min":0
                }
             }
          }
       },
       {
          "type":"text",
          "x":0,
          "y":0,
          "width":24,
          "height":3,
          "properties":{
             "markdown":"\n# AWS-EC2-API-Metrics\n"
          }
       },
       {
          "type":"text",
          "x":0,
          "y":10,
          "width":24,
          "height":1,
          "properties":{
             "markdown":"\n## **DescribeInstances**\n"
          }
       },
       {
          "type":"text",
          "x":0,
          "y":3,
          "width":24,
          "height":1,
          "properties":{
             "markdown":"\n## **All EC2 API Actions**\n"
          }
       },
       {
          "type":"text",
          "x":0,
          "y":17,
          "width":24,
          "height":1,
          "properties":{
             "markdown":"\n## **Mutable Instance API Actions**\n"
          }
       },
       {
          "type":"metric",
          "x":6,
          "y":18,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   {
                      "expression":"100*(m1/(m1+m2+m3+m4))",
                      "label":"% RunInstances API Calls Throttled",
                      "id":"e1",
                      "region":"${local.region}",
                      "yAxis":"left"
                   }
                ],
                [
                   {
                      "expression":"100*(m5/(m5+m6+m7+m8))",
                      "label":"% StartInstances API Calls Throttled",
                      "id":"e2",
                      "region":"${local.region}",
                      "yAxis":"left"
                   }
                ],
                [
                   {
                      "expression":"100*(m9/(m9+m10+m11+m12))",
                      "label":"% StopInstances API Calls Throttled",
                      "id":"e3",
                      "region":"${local.region}",
                      "yAxis":"left"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "RunInstances",
                   {
                      "id":"m1",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "SuccessfulCalls",
                   ".",
                   ".",
                   {
                      "id":"m2",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ClientErrors",
                   ".",
                   ".",
                   {
                      "id":"m3",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ServerErrors",
                   ".",
                   ".",
                   {
                      "id":"m4",
                      "visible":false
                   }
                ],
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "StartInstances",
                   {
                      "id":"m5",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "SuccessfulCalls",
                   ".",
                   ".",
                   {
                      "id":"m6",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ClientErrors",
                   ".",
                   ".",
                   {
                      "id":"m7",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ServerErrors",
                   ".",
                   ".",
                   {
                      "id":"m8",
                      "visible":false
                   }
                ],
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "StopInstances",
                   {
                      "id":"m9",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "SuccessfulCalls",
                   ".",
                   ".",
                   {
                      "id":"m10",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ClientErrors",
                   ".",
                   ".",
                   {
                      "id":"m11",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ServerErrors",
                   ".",
                   ".",
                   {
                      "id":"m12",
                      "visible":false
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"Mutable EC2 % API Calls Throttled",
             "yAxis":{
                "left":{
                   "label":"",
                   "showUnits":false,
                   "min":0,
                   "max":100
                }
             }
          }
       },
       {
          "type":"metric",
          "x":12,
          "y":18,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2/API",
                   "SuccessfulCalls",
                   "Action",
                   "RunInstances",
                   {
                      "id":"m1"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "SuccessfulCalls",
                   "Action",
                   "StartInstances",
                   {
                      "id":"m2"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "SuccessfulCalls",
                   "Action",
                   "StopInstances",
                   {
                      "id":"m3"
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"Mutable EC2 API SuccessfulCalls",
             "yAxis":{
                "left":{
                   "label":"API Calls",
                   "showUnits":false,
                   "min":0
                }
             }
          }
       },
       {
          "type":"metric",
          "x":0,
          "y":18,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "RunInstances",
                   {
                      "id":"m1"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "StartInstances",
                   {
                      "id":"m2"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "StopInstances",
                   {
                      "id":"m3"
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"Mutable EC2 API RequestLimitExceeded",
             "yAxis":{
                "left":{
                   "label":"API Calls",
                   "showUnits":false,
                   "min":0
                }
             }
          }
       },
       {
          "type":"metric",
          "x":6,
          "y":11,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   {
                      "expression":"100*(m1/(m1+m2+m3+m4))",
                      "label":"% API Calls Throttled",
                      "id":"e1",
                      "region":"${local.region}",
                      "yAxis":"left"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "DescribeInstances",
                   {
                      "id":"m1",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "SuccessfulCalls",
                   ".",
                   ".",
                   {
                      "id":"m2",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ClientErrors",
                   ".",
                   ".",
                   {
                      "id":"m3",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ServerErrors",
                   ".",
                   ".",
                   {
                      "id":"m4",
                      "visible":false
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"Describe Instances % API Calls Throttled",
             "yAxis":{
                "left":{
                   "label":"",
                   "showUnits":false,
                   "min":0,
                   "max":100
                }
             }
          }
       },
       {
          "type":"metric",
          "x":12,
          "y":11,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2/API",
                   "SuccessfulCalls",
                   "Action",
                   "DescribeInstances",
                   {
                      "id":"m1"
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"Describe Instances SuccessfulCalls",
             "yAxis":{
                "left":{
                   "label":"API Calls",
                   "showUnits":false,
                   "min":0
                }
             }
          }
       },
       {
          "type":"metric",
          "x":0,
          "y":11,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2/API",
                   "RequestLimitExceeded",
                   "Action",
                   "DescribeInstances",
                   {
                      "id":"m1"
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"Describe Instances RequestLimitExceeded",
             "yAxis":{
                "left":{
                   "label":"API Calls",
                   "showUnits":false,
                   "min":0
                }
             }
          }
       },
       {
          "type":"metric",
          "x":6,
          "y":4,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   {
                      "expression":"100*(m1/(m1+m2+m3+m4))",
                      "label":"% API Calls Throttled",
                      "id":"e1",
                      "region":"${local.region}"
                   }
                ],
                [
                   "AWS/EC2/API",
                   "ClientErrors",
                   {
                      "id":"m1",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "RequestLimitExceeded",
                   {
                      "id":"m2",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "ServerErrors",
                   {
                      "id":"m3",
                      "visible":false
                   }
                ],
                [
                   ".",
                   "SuccessfulCalls",
                   {
                      "id":"m4",
                      "visible":false
                   }
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "title":"All EC2 API Actions % API Calls Throttled",
             "yAxis":{
                "left":{
                   "label":"% API Calls Throttled",
                   "min":0,
                   "max":100,
                   "showUnits":false
                }
             }
          }
       },
       {
          "type":"metric",
          "x":12,
          "y":4,
          "width":6,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2/API",
                   "SuccessfulCalls"
                ]
             ],
             "view":"timeSeries",
             "stacked":false,
             "region":"${local.region}",
             "stat":"Sum",
             "period":60,
             "yAxis":{
                "left":{
                   "label":"API Calls",
                   "showUnits":false,
                   "min":0
                }
             },
             "title":"All EC2 API Actions SuccessfulCalls"
          }
       }
    ]
 })
}


resource "aws_cloudwatch_metric_alarm" "foobar" {
alarm_name                = "${var.Namespace}-ec2-api-requestlimit-exceeded"
comparison_operator       = "GreaterThanOrEqualToThreshold"
evaluation_periods        = "1"
metric_name               = "RequestLimitExceeded"
namespace                 = "AWS/EC2/API"
period                    = "300"
statistic                 = "Sum"
threshold                 = "1"
treat_missing_data        = "notBreaching"
alarm_actions             = [
  var.sns_topic
]
alarm_description         = "Alarm if there are EC2 API request limit exceeded "
insufficient_data_actions = []
}